### ISSUE TITLE
Rounding error when computing USDT?

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/waves#118]
This doesn't look right :sweat_smile: 

![image](https://user-images.githubusercontent.com/5486389/103980558-3213b100-51d4-11eb-8502-80af6bfe947b.png)

**Comment by bonomat** [comment]
I noticed the same the other day. The rate below is the buy rate and you are currently selling:  
Your are selling `1 BTC` for `19_000 USDT` but if you want to buy `1 BTC` it would cost you `20_000 USDT`

**Comment by thomaseizinger** [comment]
> I noticed the same the other day: The rate below is the buy rate and you are currently selling:
> Your are selling `1 BTC` for `19_000 USDT` but if you want to buy `1 BTC` it would cost you `20_000 USDT`

That is interesting!

However, there is also another rounding error because when you click the swap-asset button in the middle repeatedly, the numbers get smaller and smaller :)

**Comment by bonomat** [comment]
> However, there is also another rounding error because when you click the swap-asset button in the middle repeatedly, the numbers get smaller and smaller :)

That's also expected :D 
You would buy and sell with this rate constantly you would lose money. 

That's kind of what we achieve with swapping `alphaAmount` and `betaAmount`.

For example: Start with Alpha = BTC, and Beta=USDT

1. `alphaAmount` = `1`, `betaAmount` = `1 * 1/19000=19000`
2. swap them
3. `alphaAmount` = `19000`, `betaAmount` = `19000 * 1/20000=0.0095`
4. swap them
5. `alphaAmount` = `0.0095`, `betaAmount` = `0.0095 * 1/19000=180`


---> we should probably not swap the amounts the way how we do it

**Comment by thomaseizinger** [comment]
> That's also expected :D

Is it? My expectation was that clicking the swapping button twice brings me back to the initial state.

> ---> we should probably not swap the amounts the way how we do it

If that is the cause for it then I am voting to change to such that click the button twice results in the same state again.

**Comment by bonomat** [comment]
> If that is the cause for it then I am voting to change to such that clicking the button twice results in the same state again.

I propose achieving this by using mid-market (`buy+ask/2`) instead of `buy`/`ask` rates for calculating `beta`-amount. We should then also update the rate below the input fields for the same value.

**Comment by thomaseizinger** [comment]
> I propose achieving this by using mid-market (`buy+ask/2`) instead of `buy`/`ask` rates for calculating `beta`-amount. We should then also update the rate below the input fields for the same value.

Would bobtimus then sell to us at midmarket rate or at the given sell price?

**Comment by bonomat** [comment]
You were too fast, just edited my last response :) 

Actually I'm not a big fan of using the mid-market rate. Maybe better is to just always leave alpha amount fixed but just swap the assets.

**Comment by bonomat** [comment]
Fixed in #129
