### ISSUE TITLE
[UI Test] Wait for balance in a smart way

### ISSUE THREAD

**Issue by bonomat** [comit-network/waves#128]
Right now we use cypress to _wait_ for the swap button to be enabled which happens once we have enough funding. We hard-coded a max timeout of a few seconds which might or might not be enough as we could see on some CI runs. 

We should wait for the balance to be recognized in a smart way.

**Comment by thomaseizinger** [comment]
I think you will always have to have some kind of timeout because if you actually break something, the timeout needs to kick in and fail the test. If CI is acting up, I'd just increase the timeout to a minute or something like that.

**Comment by bonomat** [comment]
Our e2e tests have evolved and we are now asserting that the wallet has some balance.
