### ISSUE TITLE
Move code from `elements-fun` into `rust-elements`

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/waves#130]
It turns out that there isn't as much need for most of the re-modelling that we did in elements-fun as we initially thought. See more [here](https://github.com/ElementsProject/rust-elements/issues/67#issuecomment-759836973).

This is a tracking issue for moving all of what we did in elements-fun back into rust-elements (non-exhaustive list):

- [x] Add a dependency to `rust-secp256k1-zkp` and model asset/value commitment using types from `rust-secp256k1-zkp`
- [x] Create `TxOut` constructors for `new_last_confidential` / `new_non_last_confidential`
- [x] Introduce `.unblind` API on `TxOut`
- [x] Introduce `ExplicitTxOut` and `ConfidentialTxOut` along with `into_{explicit,confidential}` on `TxOut`

**Comment by luckysori** [comment]
This is so done.
