### ISSUE TITLE
Verify frontend wallet's {BTC, USDt} asset ID at compile time

### ISSUE THREAD

**Issue by luckysori** [comit-network/waves#135]
_Originally posted by @thomaseizinger in https://github.com/comit-network/waves/pull/134#discussion_r570774181_

With #134 we no longer verify the validity of `{NATIVE, USDT}_ASSET_ID` at compile time. This means we can build the application with wrong values and only fail during execution time.

**Comment by bonomat** [comment]
Not needed atm.
