### ISSUE TITLE
Sign and send in extension is broken

### ISSUE THREAD

**Issue by bonomat** [comit-network/waves#244]
We have the following flow if a user wants to trade against bobtimus: 

1. go to `Trade` tab. 
2. fill in desired BTC or USDT amount
3. manually open extension page
4. click `Sign and Send`
5. the extension page should redirect to _home_ where balances, etc are shown
6. the web app should redirect `/swapped/tx/123e41....`

At the moment step 5 is broken, i.e. the user stays on the `Sign and Send` page. Signing works and the web app gets redirected.

**Comment by bonomat** [comment]
cc @thomaseizinger: this could have something todo with your refactoring.

**Comment by thomaseizinger** [comment]
Interesting. This isn't covered by the tests then?

On that front: We don't have proper routing in the extension yet. Would be a good thing to add. The current state keeping and decision making what is being rendered is error prone as we can see.

**Comment by bonomat** [comment]
> Interesting. This isn't covered by the tests then?

The test only covers that the signing and sending (i.e. the swap) was successful. It stops afterwards :)
